yolo_model:

  config_file:
    name: yolov4-tiny-custom.cfg
  weight_file:
    name: yolov4-tiny-custom_best.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - bake
      - bake2
      #- intellibake
      

